### ISSUE TITLE
Refresh on tab refresh

### ISSUE THREAD

**Issue by nvwieren** [mendix/GridSelector#3] opened 2016-10-18 06:49 UTC
As of 6.9.0 when the Checkbox grid selector is part of a page holder where the tab has Refresh on open configured, the grid is not refreshed. .update is not triggered at all.

This is specific to the situation where you have a Checkbox grid selector in a pageholder, which in itself is contained in a dataview.

**Comment by nvwieren** [comment] 2016-10-27 12:08
Any idea on when you have time to have a look at this?

**Comment by nvwieren** [comment] 2016-10-28 06:22
@JelteMX I've created a fork and updated the test project to 6.9.0 + changed the logic of the test project to reflect the situation in our application, which broke when we moved to 6.9.0.

The tab containing the Checkbox grid selector has "Refresh on show" enabled, which (at least in 6.5.1) made sure the grid was refreshed. In case any top or left items were added, this would be reflected there which it isn't anymore. 

The .update functions is not triggered anymore when the tab is opened. It btw is when you don't have a Dataview around the Tab container. I've looked through the _widgetBase and DataView code and I see a lot has changed, but can't seem to find the exact problem - though I know things specific to object update has been changed in 6.8.0 (performance).

This issue is keeping us from moving from 6.5.1 to 6.9.0, which in our case is necessary to be able to implement performance enhancements that we developed with Mendix staff.

[https://github.com/nvwieren/GridSelector/commit/ce8cf33440bc4bf586aaffe0cde7993166d8e271](https://github.com/nvwieren/GridSelector/commit/ce8cf33440bc4bf586aaffe0cde7993166d8e271)

**Comment by Rvthof** [comment] 2016-10-28 09:30
Hi Nick,

Jelte is currently on vacation. I had a look at the test project, but I think I'm missing some data for it to be a precise reproduction of your issue.
I did make a new version based on your description, that might fix the issue. Can you try if this one works for you?

https://github.com/mendix/GridSelector/tree/update-fix
You can download the mpk directly from the test/widgets/ folder there.

It's pretty simple, it sets a subscribe to the context object in the update itself, which in turn calls this.update again.

**Comment by nvwieren** [comment] 2016-10-28 10:03
Hi Richard,

Thanks for helping me out. I've added your fix to the fork but it fails because the subscribe now sends the guid as parameter to .update, which expects an actual object+callback. The obj.getGuid() now fails.

In 6.5.1 the "Refresh on open" of a tab would trigger the .update of all children widgets. In 6.9.0 this is not the case. So if you add/delete a vehicle or color these changes are not reflected. I think the data should be complete. Could your try to delete the database folder in your deployment?

The afterStartup created a ParentEntity object and should relate all Vehicles/Colors to it.

If a phone-call would be quicker, please let me know.


Thanks,
Nick

**Comment by Rvthof** [comment] 2016-10-28 10:09
My name is Robert! :)
The parent entity does not get any vehicles or colors set to it and there seems to be no way to add them besides the widget, so I had to remove the xpath constraints on the widget.

It seems it is only subscribing to changes to the objects it already had. I figured triggering the update when the parent object was changed would suffice. I can fix the guid instead of object, that should help.

**Comment by Rvthof** [comment] 2016-10-28 12:08
Ive added a new version to the update-fix branch. Can you try that one?

**Comment by nvwieren** [comment] 2016-10-28 12:49
Hi Richard, I've tried your change on my testproject > now when I click an option, all options on the same line (which have no relation at all) get unchecked, including the option that I just clicked. I just re-cloned my GridSelector version and all data is properly created. Did you cleanly clone my version (https://github.com/nvwieren/GridSelector)?

**Comment by Rvthof** [comment] 2016-10-28 12:50
Ok, guess it will have to wait till Jelte is back then.

**Comment by nvwieren** [comment] 2016-10-28 13:08
Ok, could you please tell me if you were able to see the same issue as me?

**Comment by Rvthof** [comment] 2016-10-28 13:14
I don't seem to have this issue, no. It seems to be working as it should in my test project.
Maybe this is related to the xpath constraints on the top and left, as I had to remove these for the objects to show up?

**Comment by nvwieren** [comment] 2016-10-28 13:17
Ok, but you did start with a clean database, as the after startup will not update existing data..

**Comment by Rvthof** [comment] 2016-10-28 13:23
Just tried with a completely fresh database, works as intended.
I did put the constraints back, as that may have been because of a different issue why I wasn't seeing the objects and those work now as well.

**Comment by nvwieren** [comment] 2016-10-28 13:26
Ok, good to hear. Just wanted to make sure you have a reproducible case on your end.

**Comment by nvwieren** [comment] 2016-10-31 11:25
Is Jelte back this week?

**Comment by Rvthof** [comment] 2016-11-01 13:33
No, next week.

**Comment by nvwieren** [comment] 2016-11-02 10:40
6.10 seems to solve the problem of the tab page not triggering the .update method of child widgets in tabContent, but I would love to know in relation to what release note this was achieved as I'm unable to find anything related there..

**Comment by JelteMX** [comment] 2016-11-02 20:22
Hi @nvwieren I'm back next week. I have a list of widget issues open for next week and the week after, I'll be sure to look into your problem as well. I'll check the release notes as well to see what has changed for the WebUI team in relation to your issue.

**Comment by nvwieren** [comment] 2016-11-17 11:21
hi @JelteMX any update on this?

**Comment by JelteMX** [comment] 2016-12-01 14:57
I'm working on a fix. Did some cleanup. Need to get the subscriptions working first.
Regarding the tab not calling ``.update``, this is an R&D problem. So if it's fixed in 6.10, then it should be in the Release Notes. If not, file a ticket for it

**Comment by JelteMX** [comment] 2016-12-01 15:19
Update: Fixed the subscriptions, so it will call correctly when you update the context object. (This I tested with your test-project). As the ``.update`` issue is resolved in 6.10 and not related to this widget, I am closing the issue. Will create a new release and update in the AppStore

**Closed by JelteMX** 2016-12-01 15:19 UTC
